<html>
	<div class="">
		<label for="nacionalidade">Nacionalidade: </label>
		<select class="form-control" name="nacionalidade" style="height:80px;">
        <option value="AF">Afeganistão (‫افغانستان‬‎)</option>
        <option value="ZA">África do Sul (South Africa)</option>
        <option value="AL">Albânia (Shqipëri)</option>
        <option value="DE">Alemanha (Deutschland)</option>
        <option value="AD">Andorra</option>
        <option value="AO">Angola</option>
        <option value="AI">Anguilla</option>
        <option value="AQ">Antártida (Antarctica)</option>
        <option value="AG">Antígua e Barbuda (Antigua and Barbuda)</option>
        <option value="SA">Arábia Saudita (‫المملكة العربية السعودية‬‎)</option>
        <option value="DZ">Argélia (‫الجزائر‬‎)</option>
        <option value="AR">Argentina</option>
        <option value="AM">Armênia (Հայաստան)</option>
        <option value="AW">Aruba</option>
        <option value="AU">Austrália (Australia)</option>
        <option value="AT">Áustria (Österreich)</option>
        <option value="AZ">Azerbaijão (Azərbaycan)</option>
        <option value="BS">Bahamas</option>
        <option value="BH">Bahrein (‫البحرين‬‎)</option>
        <option value="BD">Bangladesh (বাংলাদেশ)</option>
        <option value="BB">Barbados</option>
        <option value="BE">Bélgica (België)</option>
        <option value="BZ">Belize</option>
        <option value="BJ">Benin (Bénin)</option>
        <option value="BM">Bermudas (Bermuda)</option>
        <option value="BY">Bielorrússia (Беларусь)</option>
        <option value="BO">Bolívia (Bolivia)</option>
        <option value="BA">Bósnia e Herzegovina (Босна и Херцеговина)</option>
        <option value="BW">Botsuana (Botswana)</option>
        <option value="BR" selected>Brasil</option>
        <option value="BN">Brunei</option>
        <option value="BG">Bulgária (България)</option>
        <option value="BF">Burquina Faso (Burkina Faso)</option>
        <option value="BI">Burundi (Uburundi)</option>
        <option value="BT">Butão (འབྲུག)</option>
        <option value="CV">Cabo Verde (Kabu Verdi)</option>
        <option value="KH">Camboja (កម្ពុជា)</option>
        <option value="CA">Canadá (Canada)</option>
        <option value="QA">Catar (‫قطر‬‎)</option>
        <option value="KZ">Cazaquistão (Казахстан)</option>
        <option value="EA">Ceuta e Melilha (Ceuta y Melilla)</option>
        <option value="TD">Chade (Tchad)</option>
        <option value="CL">Chile</option>
        <option value="CN">China (中国)</option>
        <option value="CY">Chipre (Κύπρος)</option>
        <option value="VA">Cidade do Vaticano (Città del Vaticano)</option>
        <option value="SG">Cingapura (Singapore)</option>
        <option value="CO">Colômbia (Colombia)</option>
        <option value="KM">Comores (‫جزر القمر‬‎)</option>
        <option value="CG">Congo - Brazzaville (Congo-Brazzaville)</option>
        <option value="CD">Congo - Kinshasa (Jamhuri ya Kidemokrasia ya Kongo)</option>
        <option value="KP">Coreia do Norte (조선 민주주의 인민 공화국)</option>
        <option value="KR">Coreia do Sul (대한민국)</option>
        <option value="CI">Costa do Marfim (Côte d’Ivoire)</option>
        <option value="CR">Costa Rica</option>
        <option value="HR">Croácia (Hrvatska)</option>
        <option value="CU">Cuba</option>
        <option value="CW">Curaçao</option>
        <option value="DG">Diego Garcia</option>
        <option value="DK">Dinamarca (Danmark)</option>
        <option value="DJ">Djibuti (Djibouti)</option>
        <option value="DM">Dominica</option>
        <option value="EG">Egito (‫مصر‬‎)</option>
        <option value="SV">El Salvador</option>
        <option value="AE">Emirados Árabes Unidos (‫الإمارات العربية المتحدة‬‎)</option>
        <option value="EC">Equador (Ecuador)</option>
        <option value="ER">Eritreia (Eritrea)</option>
        <option value="SK">Eslováquia (Slovensko)</option>
        <option value="SI">Eslovênia (Slovenija)</option>
        <option value="ES">Espanha (España)</option>
        <option value="US">Estados Unidos (United States)</option>
        <option value="EE">Estônia (Eesti)</option>
        <option value="ET">Etiópia (Ethiopia)</option>
        <option value="FJ">Fiji</option>
        <option value="PH">Filipinas (Philippines)</option>
        <option value="FI">Finlândia (Suomi)</option>
        <option value="FR">França (France)</option>
        <option value="GA">Gabão (Gabon)</option>
        <option value="GM">Gâmbia (Gambia)</option>
        <option value="GH">Gana (Gaana)</option>
        <option value="GE">Geórgia (საქართველო)</option>
        <option value="GS">Geórgia do Sul e Ilhas Sandwich do Sul (South Georgia &amp; South Sandwich Islands)</option>
        <option value="GI">Gibraltar</option>
        <option value="GD">Granada (Grenada)</option>
        <option value="GR">Grécia (Ελλάδα)</option>
        <option value="GL">Groênlandia (Kalaallit Nunaat)</option>
        <option value="GP">Guadalupe (Guadeloupe)</option>
        <option value="GU">Guam</option>
        <option value="GT">Guatemala</option>
        <option value="GG">Guernsey</option>
        <option value="GY">Guiana (Guyana)</option>
        <option value="GF">Guiana Francesa (Guyane française)</option>
        <option value="GN">Guiné (Guinée)</option>
        <option value="GW">Guiné Bissau</option>
        <option value="GQ">Guiné Equatorial (Guinea Ecuatorial)</option>
        <option value="HT">Haiti</option>
        <option value="NL">Holanda (Nederland)</option>
        <option value="HN">Honduras</option>
        <option value="HK">Hong Kong (香港)</option>
        <option value="HU">Hungria (Magyarország)</option>
        <option value="YE">Iêmen (‫اليمن‬‎)</option>
        <option value="BV">Ilha Bouvet (Bouvet Island)</option>
        <option value="AC">Ilha de Ascensão (Ascension Island)</option>
        <option value="CP">Ilha de Clipperton (Clipperton Island)</option>
        <option value="IM">Ilha de Man (Isle of Man)</option>
        <option value="HM">Ilha Heard e Ilhas McDonald (Heard &amp; McDonald Islands)</option>
        <option value="NF">Ilha Norfolk (Norfolk Island)</option>
        <option value="AX">Ilhas Åland (Åland)</option>
        <option value="KY">Ilhas Caiman (Cayman Islands)</option>
        <option value="IC">Ilhas Canárias (islas Canarias)</option>
        <option value="CC">Ilhas Coco (Kepulauan Cocos (Keeling))</option>
        <option value="CK">Ilhas Cook (Cook Islands)</option>
        <option value="UM">Ilhas Distantes dos EUA (U.S. Outlying Islands)</option>
        <option value="FO">Ilhas Faroe (Føroyar)</option>
        <option value="FK">Ilhas Malvinas (Falkland Islands (Islas Malvinas))</option>
        <option value="MP">Ilhas Marianas do Norte (Northern Mariana Islands)</option>
        <option value="MH">Ilhas Marshall (Marshall Islands)</option>
        <option value="CX">Ilhas Natal (Christmas Island)</option>
        <option value="PN">Ilhas Pitcairn (Pitcairn Islands)</option>
        <option value="SB">Ilhas Salomão (Solomon Islands)</option>
        <option value="TC">Ilhas Turks e Caicos (Turks and Caicos Islands)</option>
        <option value="VG">Ilhas Virgens Britânicas (British Virgin Islands)</option>
        <option value="VI">Ilhas Virgens dos EUA (U.S. Virgin Islands)</option>
        <option value="IN">Índia (भारत)</option>
        <option value="ID">Indonésia (Indonesia)</option>
        <option value="IR">Irã (‫ایران‬‎)</option>
        <option value="IQ">Iraque (‫العراق‬‎)</option>
        <option value="IE">Irlanda (Ireland)</option>
        <option value="IS">Islândia (Ísland)</option>
        <option value="IL">Israel (‫ישראל‬‎)</option>
        <option value="IT">Itália (Italia)</option>
        <option value="JM">Jamaica</option>
        <option value="JP">Japão (日本)</option>
        <option value="JE">Jersey</option>
        <option value="JO">Jordânia (‫الأردن‬‎)</option>
        <option value="XK">Kosovo (Kosovë)</option>
        <option value="KW">Kuwait (‫الكويت‬‎)</option>
        <option value="LA">Laos (ລາວ)</option>
        <option value="LS">Lesoto (Lesotho)</option>
        <option value="LV">Letônia (Latvija)</option>
        <option value="LB">Líbano (‫لبنان‬‎)</option>
        <option value="LR">Libéria (Liberia)</option>
        <option value="LY">Líbia (‫ليبيا‬‎)</option>
        <option value="LI">Liechtenstein</option>
        <option value="LT">Lituânia (Lietuva)</option>
        <option value="LU">Luxemburgo (Luxembourg)</option>
        <option value="MO">Macau (澳門)</option>
        <option value="MK">Macedônia (Македонија)</option>
        <option value="MG">Madagascar (Madagasikara)</option>
        <option value="MY">Malásia (Malaysia)</option>
        <option value="MW">Malawi</option>
        <option value="MV">Maldivas (Maldives)</option>
        <option value="ML">Mali</option>
        <option value="MT">Malta</option>
        <option value="MA">Marrocos (‫المغرب‬‎)</option>
        <option value="MQ">Martinica (Martinique)</option>
        <option value="MU">Maurício (Moris)</option>
        <option value="MR">Mauritânia (‫موريتانيا‬‎)</option>
        <option value="YT">Mayotte</option>
        <option value="MX">México</option>
        <option value="MM">Mianmar (Birmânia) (မြန်မာ)</option>
        <option value="FM">Micronésia (Micronesia)</option>
        <option value="MZ">Moçambique</option>
        <option value="MD">Moldávia (Republica Moldova)</option>
        <option value="MC">Mônaco (Monaco)</option>
        <option value="MN">Mongólia (Монгол)</option>
        <option value="ME">Montenegro (Crna Gora)</option>
        <option value="MS">Montserrat</option>
        <option value="NA">Namíbia (Namibië)</option>
        <option value="NR">Nauru</option>
        <option value="NP">Nepal (नेपाल)</option>
        <option value="NI">Nicarágua (Nicaragua)</option>
        <option value="NE">Níger (Nijar)</option>
        <option value="NG">Nigéria (Nigeria)</option>
        <option value="NU">Niue</option>
        <option value="NO">Noruega (Norge)</option>
        <option value="NC">Nova Caledônia (Nouvelle-Calédonie)</option>
        <option value="NZ">Nova Zelândia (New Zealand)</option>
        <option value="OM">Omã (‫عُمان‬‎)</option>
        <option value="BQ">Países Baixos Caribenhos (Caribbean Netherlands)</option>
        <option value="PW">Palau</option>
        <option value="PS">Palestina (‫فلسطين‬‎)</option>
        <option value="PA">Panamá</option>
        <option value="PG">Papua-Nova Guiné (Papua New Guinea)</option>
        <option value="PK">Paquistão (‫پاکستان‬‎)</option>
        <option value="PY">Paraguai (Paraguay)</option>
        <option value="PE">Peru (Perú)</option>
        <option value="PF">Polinésia Francesa (Polynésie française)</option>
        <option value="PL">Polônia (Polska)</option>
        <option value="PR">Porto Rico (Puerto Rico)</option>
        <option value="PT">Portugal</option>
        <option value="KE">Quênia (Kenya)</option>
        <option value="KG">Quirguistão (Кыргызстан)</option>
        <option value="KI">Quiribati (Kiribati)</option>
        <option value="GB">Reino Unido (United Kingdom)</option>
        <option value="CF">República Centro-Africana (République centrafricaine)</option>
        <option value="DO">República Dominicana</option>
        <option value="CM">República dos Camarões (Cameroun)</option>
        <option value="CZ">República Tcheca (Česká republika)</option>
        <option value="RE">Reunião (La Réunion)</option>
        <option value="RO">Romênia (România)</option>
        <option value="RW">Ruanda (Rwanda)</option>
        <option value="RU">Rússia (Россия)</option>
        <option value="EH">Saara Ocidental (‫الصحراء الغربية‬‎)</option>
        <option value="PM">Saint Pierre e Miquelon (Saint-Pierre-et-Miquelon)</option>
        <option value="WS">Samoa</option>
        <option value="AS">Samoa Americana (American Samoa)</option>
        <option value="SM">San Marino</option>
        <option value="SH">Santa Helena (Saint Helena)</option>
        <option value="LC">Santa Lúcia (Saint Lucia)</option>
        <option value="BL">São Bartolomeu (Saint-Barthélemy)</option>
        <option value="KN">São Cristovão e Nevis (Saint Kitts and Nevis)</option>
        <option value="MF">São Martinho (Saint-Martin (partie française))</option>
        <option value="ST">São Tomé e Príncipe</option>
        <option value="VC">São Vicente e Granadinas (St. Vincent &amp; Grenadines)</option>
        <option value="SN">Senegal (Sénégal)</option>
        <option value="SL">Serra Leoa (Sierra Leone)</option>
        <option value="RS">Sérvia (Србија)</option>
        <option value="SC">Seychelles</option>
        <option value="SX">Sint Maarten</option>
        <option value="SY">Síria (‫سوريا‬‎)</option>
        <option value="SO">Somália (Soomaaliya)</option>
        <option value="LK">Sri Lanka (ශ්‍රී ලංකාව)</option>
        <option value="SZ">Suazilândia (Swaziland)</option>
        <option value="SD">Sudão (‫السودان‬‎)</option>
        <option value="SS">Sudão do Sul (‫جنوب السودان‬‎)</option>
        <option value="SE">Suécia (Sverige)</option>
        <option value="CH">Suíça (Schweiz)</option>
        <option value="SR">Suriname</option>
        <option value="SJ">Svalbard e Jan Mayen (Svalbard og Jan Mayen)</option>
        <option value="TJ">Tadjiquistão (Tajikistan)</option>
        <option value="TH">Tailândia (ไทย)</option>
        <option value="TW">Taiwan (台灣)</option>
        <option value="TZ">Tanzânia (Tanzania)</option>
        <option value="IO">Território Britânico do Oceano Índico (British Indian Ocean Territory)</option>
        <option value="TF">Territórios Franceses do Sul (Terres australes françaises)</option>
        <option value="TL">Timor-Leste</option>
        <option value="TG">Togo</option>
        <option value="TK">Tokelau</option>
        <option value="TO">Tonga</option>
        <option value="TT">Trinidad e Tobago (Trinidad and Tobago)</option>
        <option value="TA">Tristão da Cunha (Tristan da Cunha)</option>
        <option value="TN">Tunísia (‫تونس‬‎)</option>
        <option value="TM">Turcomenistão (Turkmenistan)</option>
        <option value="TR">Turquia (Türkiye)</option>
        <option value="TV">Tuvalu</option>
        <option value="UA">Ucrânia (Україна)</option>
        <option value="UG">Uganda</option>
        <option value="UY">Uruguai (Uruguay)</option>
        <option value="UZ">Uzbequistão (Oʻzbekiston)</option>
        <option value="VU">Vanuatu</option>
        <option value="VE">Venezuela</option>
        <option value="VN">Vietnã (Việt Nam)</option>
        <option value="WF">Wallis e Futuna (Wallis and Futuna)</option>
        <option value="ZM">Zâmbia (Zambia)</option>
        <option value="ZW">Zimbábue (Zimbabwe)</option>
    </select>
	</div>
</html>